export const hygieneProducts = [
  { id: "toothbrush", name: "Toothbrush", emoji: "🪥", color: "bg-green-100", borderColor: "border-green-500" },
  { id: "toothpaste", name: "Toothpaste", emoji: "🦷", color: "bg-yellow-100", borderColor: "border-yellow-500" },
  { id: "soap", name: "Soap", emoji: "🧼", color: "bg-green-50", borderColor: "border-green-400" },
  { id: "shampoo", name: "Shampoo", emoji: "🧴", color: "bg-yellow-50", borderColor: "border-yellow-400" },
  { id: "towel", name: "Towel", emoji: "🛁", color: "bg-green-100", borderColor: "border-green-500" },
  { id: "comb", name: "Comb", emoji: "💇", color: "bg-yellow-100", borderColor: "border-yellow-500" },
  { id: "tissues", name: "Tissues", emoji: "🤧", color: "bg-green-50", borderColor: "border-green-400" },
  { id: "hand_sanitizer", name: "Hand Sanitizer", emoji: "🫧", color: "bg-yellow-50", borderColor: "border-yellow-400" },
  { id: "cotton_buds", name: "Cotton Buds", emoji: "🏥", color: "bg-green-100", borderColor: "border-green-500" },
  { id: "sunscreen", name: "Sunscreen", emoji: "☀️", color: "bg-yellow-100", borderColor: "border-yellow-500" },
  { id: "deodorant", name: "Deodorant", emoji: "🌸", color: "bg-green-50", borderColor: "border-green-400" },
  { id: "nail_clipper", name: "Nail Clipper", emoji: "✂️", color: "bg-yellow-50", borderColor: "border-yellow-400" },
  { id: "q_tips", name: "Q-Tips", emoji: "🫧", color: "bg-green-100", borderColor: "border-green-500" },
  { id: "shoe_powder", name: "Shoe Powder", emoji: "👟", color: "bg-yellow-100", borderColor: "border-yellow-500" },
  { id: "conditioner", name: "Conditioner", emoji: "💆", color: "bg-green-50", borderColor: "border-green-400" },
  { id: "cologne", name: "Cologne", emoji: "🧴", color: "bg-yellow-50", borderColor: "border-yellow-400" },
  { id: "perfume", name: "Perfume", emoji: "🌷", color: "bg-green-100", borderColor: "border-green-500" },
];

export const sportsProducts = [
  { id: "cleats_football", name: "Football Cleats", emoji: "🏈", color: "bg-green-700", borderColor: "border-yellow-400" },
  { id: "cleats_soccer", name: "Soccer Cleats", emoji: "⚽", color: "bg-yellow-400", borderColor: "border-green-700" },
  { id: "cleats_baseball", name: "Baseball Cleats", emoji: "⚾", color: "bg-green-800", borderColor: "border-yellow-400" },
  { id: "cleats_lacrosse", name: "Lacrosse Cleats", emoji: "🥍", color: "bg-yellow-400", borderColor: "border-green-700" },
  { id: "helmet_football", name: "Football Helmet", emoji: "🏈", color: "bg-green-700", borderColor: "border-yellow-400" },
  { id: "helmet_baseball", name: "Baseball Helmet", emoji: "⚾", color: "bg-yellow-400", borderColor: "border-green-700" },
  { id: "helmet_softball", name: "Softball Helmet", emoji: "🥎", color: "bg-green-800", borderColor: "border-yellow-400" },
  { id: "helmet_lacrosse", name: "Lacrosse Helmet", emoji: "🥍", color: "bg-yellow-400", borderColor: "border-green-700" },
  { id: "helmet_hockey", name: "Hockey Helmet", emoji: "🏒", color: "bg-green-700", borderColor: "border-yellow-400" },
  { id: "helmet_cycling", name: "Cycling Helmet", emoji: "🚴", color: "bg-yellow-400", borderColor: "border-green-700" },
  { id: "shoes_wrestling", name: "Wrestling Shoes", emoji: "🤼", color: "bg-green-800", borderColor: "border-yellow-400" },
  { id: "shoes_basketball", name: "Basketball Shoes", emoji: "🏀", color: "bg-yellow-400", borderColor: "border-green-700" },
  { id: "shoes_running", name: "Running Shoes", emoji: "👟", color: "bg-green-700", borderColor: "border-yellow-400" },
  { id: "sweatpants", name: "Sweatpants", emoji: "🩲", color: "bg-yellow-400", borderColor: "border-green-700" },
  { id: "sweatshirt", name: "Sweatshirt", emoji: "🧥", color: "bg-green-800", borderColor: "border-yellow-400" },
  { id: "rain_jacket", name: "Rain Jacket", emoji: "🌧️", color: "bg-yellow-400", borderColor: "border-green-700" },
  { id: "rain_pants", name: "Rain Pants", emoji: "🌂", color: "bg-green-700", borderColor: "border-yellow-400" },
  { id: "sports_tshirt", name: "Sports T-Shirt", emoji: "👕", color: "bg-yellow-400", borderColor: "border-green-700" },
  { id: "sports_shorts", name: "Sports Shorts", emoji: "🩳", color: "bg-green-800", borderColor: "border-yellow-400" },
  { id: "sports_socks", name: "Sports Socks", emoji: "🧦", color: "bg-yellow-400", borderColor: "border-green-700" },
  { id: "sports_bag", name: "Sports Bag", emoji: "🎒", color: "bg-green-700", borderColor: "border-yellow-400" },
  { id: "sports_water_bottle", name: "Water Bottle", emoji: "🥤", color: "bg-yellow-400", borderColor: "border-green-700" },
  { id: "sports_gloves", name: "Sports Gloves", emoji: "🥊", color: "bg-green-800", borderColor: "border-yellow-400" },
  { id: "sports_knee_pads", name: "Knee Pads", emoji: "🦵", color: "bg-yellow-400", borderColor: "border-green-700" },
  { id: "sports_equipment", name: "Equipment Needed", emoji: "🏆", color: "bg-green-700", borderColor: "border-yellow-400" },
];

export const clothesProducts = [
  { id: "tshirt", name: "T-Shirt", emoji: "👕", color: "bg-green-100", borderColor: "border-green-500" },
  { id: "pants", name: "Pants", emoji: "👖", color: "bg-yellow-100", borderColor: "border-yellow-500" },
  { id: "dress", name: "Dress", emoji: "👗", color: "bg-green-50", borderColor: "border-green-400" },
  { id: "shoes", name: "Shoes", emoji: "👟", color: "bg-yellow-50", borderColor: "border-yellow-400" },
  { id: "socks", name: "Socks", emoji: "🧦", color: "bg-green-100", borderColor: "border-green-500" },
  { id: "jacket", name: "Jacket", emoji: "🧥", color: "bg-yellow-100", borderColor: "border-yellow-500" },
  { id: "hat", name: "Hat", emoji: "🧢", color: "bg-green-50", borderColor: "border-green-400" },
  { id: "scarf", name: "Scarf", emoji: "🧣", color: "bg-yellow-50", borderColor: "border-yellow-400" },
  { id: "gloves", name: "Gloves", emoji: "🧤", color: "bg-green-100", borderColor: "border-green-500" },
  { id: "shorts", name: "Shorts", emoji: "🩳", color: "bg-yellow-100", borderColor: "border-yellow-500" },
  { id: "pajamas", name: "Pajamas", emoji: "😴", color: "bg-green-50", borderColor: "border-green-400" },
  { id: "underwear", name: "Underwear", emoji: "🩲", color: "bg-yellow-50", borderColor: "border-yellow-400" },
];